{
   "no_index" : {
      "directory" : [
         "t",
         "inc"
      ]
   },
   "meta-spec" : {
      "version" : 1.4,
      "url" : "http://module-build.sourceforge.net/META-spec-v1.4.html"
   },
   "generated_by" : "ExtUtils::MakeMaker version 6.56",
   "distribution_type" : "module",
   "version" : "0.92",
   "name" : "AnyEvent-HTTPD",
   "author" : [
      "Robin Redeker <elmex@ta-sa.org>"
   ],
   "license" : "perl",
   "build_requires" : {
      "ExtUtils::MakeMaker" : 0
   },
   "requires" : {
      "Compress::Zlib" : 0,
      "bytes" : 0,
      "URI" : 0,
      "AnyEvent" : 0,
      "Object::Event" : 0,
      "AnyEvent::HTTP" : 0,
      "Test::More" : 0,
      "Time::Local" : 0,
      "common::sense" : 0
   },
   "abstract" : "A simple lightweight event based web (application) server",
   "configure_requires" : {
      "ExtUtils::MakeMaker" : 0
   }
}
