--- #YAML:1.0
name:                AnyEvent-HTTPD
version:             0.03
abstract:            A simple lightweight event based web (application) server
license:             perl
author:              
    - Robin Redeker <elmex@ta-sa.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           0
    Fcntl:                         0
    HTTP::Date:                    0
    Object::Event:                 0
    POSIX:                         0
    Test::More:                    0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
