--- #YAML:1.0
name:               AnyEvent-HTTPD
version:            0.84
abstract:           A simple lightweight event based web (application) server
author:
    - Robin Redeker <elmex@ta-sa.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:       0
    common::sense:  0
    Object::Event:  0
    Test::More:     0
    Time::Local:    0
    URI:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
